// Mock data for when the API is unavailable
export const mockFeed = [
  {
    id: "feed-1",
    type: "protection",
    title: "Stripe API Key Intercepted",
    body: "A Stripe secret key (sk_live_...) was detected in a clipboard capture and automatically redacted before storage.",
    reasoning: "Protecting sensitive credentials is always top priority.",
    actions: [
      { id: "view", label: "View Redacted" },
      { id: "dismiss", label: "Dismiss" },
    ],
  },
  {
    id: "feed-2",
    type: "insight",
    title: "Heavy Focus on Agent Architectures",
    body: "4 articles about AI agents captured today, but nothing about deployment or infrastructure.",
    reasoning: "Noticed a strong pattern in your reading — you might be in deep research mode.",
    actions: [
      { id: "interesting", label: "Interesting" },
      { id: "dismiss", label: "Dismiss" },
    ],
  },
  {
    id: "feed-3",
    type: "learning",
    title: "What's Your Primary Role?",
    body: "I've seen code snippets, architecture docs, and API designs. Are you backend, frontend, or fullstack?",
    reasoning: "Knowing your role helps me prioritize and categorize captures better.",
    actions: [
      { id: "backend", label: "Backend" },
      { id: "frontend", label: "Frontend" },
      { id: "fullstack", label: "Fullstack" },
      { id: "skip", label: "Skip" },
    ],
  },
  {
    id: "feed-4",
    type: "captured",
    title: "3 New Captures Today",
    body: "A Python snippet from VS Code, a research paper from Chrome, and a Slack conversation.",
    reasoning: "Daily summary of what I've ingested for your review.",
    actions: [
      { id: "browse", label: "Browse" },
      { id: "dismiss", label: "Dismiss" },
    ],
  },
  {
    id: "feed-5",
    type: "forgotten",
    title: "Pasta Carbonara Recipe — Fading",
    body: "You saved this recipe 5 days ago but haven't revisited it. Should I keep it prominent?",
    reasoning: "Older unrevisited captures get deprioritized unless you say otherwise.",
    actions: [
      { id: "remind", label: "Remind Me" },
      { id: "dismiss", label: "Dismiss" },
    ],
  },
  {
    id: "feed-6",
    type: "synthesis",
    title: "Pattern: You're Building an Agent",
    body: "Across 12 captures, I see a recurring theme — agent orchestration, tool calling, memory systems. You're building something.",
    reasoning: "Synthesis of multiple captures into a higher-level insight.",
    actions: [
      { id: "tell-more", label: "Tell Me More" },
      { id: "dismiss", label: "Dismiss" },
    ],
  },
];

export const mockStreamEvents = [
  { type: "CAPTURE", message: "New clipboard capture from VS Code", timestamp: new Date(Date.now() - 5000).toISOString() },
  { type: "AIRIA", message: "Classifying capture as 'code' (confidence: 0.94)", timestamp: new Date(Date.now() - 12000).toISOString() },
  { type: "DLP", message: "Scanning for PII... clean", timestamp: new Date(Date.now() - 18000).toISOString() },
  { type: "BRAINTRUST", message: "Quality score: 0.87 — above threshold", timestamp: new Date(Date.now() - 25000).toISOString() },
  { type: "REFLECTION", message: "No retry needed — score meets baseline", timestamp: new Date(Date.now() - 30000).toISOString() },
  { type: "SYNTHESIS", message: "Running cross-capture analysis...", timestamp: new Date(Date.now() - 45000).toISOString() },
  { type: "QUESTION", message: "Queuing learning question about user role", timestamp: new Date(Date.now() - 60000).toISOString() },
  { type: "CAPTURE", message: "New capture from Chrome — research paper", timestamp: new Date(Date.now() - 90000).toISOString() },
  { type: "AIRIA", message: "Classifying as 'research' (confidence: 0.91)", timestamp: new Date(Date.now() - 95000).toISOString() },
  { type: "DLP", message: "PII detected: email address redacted", timestamp: new Date(Date.now() - 120000).toISOString() },
];

export const mockCaptures = [
  {
    id: "cap-1",
    category: "code",
    summary: "Python async agent coordinator",
    content: "class CapsuleCoordinator(Agent): async def process_capture(self, content: str)...",
    source: "VS Code",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    tags: ["python", "agents", "async"],
    has_pii: false,
    scores: { quality: 0.92 },
  },
  {
    id: "cap-2",
    category: "recipe",
    summary: "Pasta Carbonara — Classic Roman Style",
    content: "Guanciale, eggs, pecorino romano, black pepper. No cream. Cook the guanciale until crispy...",
    source: "Chrome",
    timestamp: new Date(Date.now() - 432000000).toISOString(),
    tags: ["italian", "pasta", "quick"],
    has_pii: false,
    scores: { quality: 0.78 },
  },
  {
    id: "cap-3",
    category: "research",
    summary: "ReAct: Synergizing Reasoning and Acting",
    content: "Language models can generate reasoning traces and task-specific actions in an interleaved manner...",
    source: "Chrome",
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    tags: ["llm", "reasoning", "papers"],
    has_pii: false,
    scores: { quality: 0.95 },
  },
  {
    id: "cap-4",
    category: "communication",
    summary: "Team standup notes — Sprint 14",
    content: "Discussed: agent memory system, DLP integration, quality scoring pipeline...",
    source: "Slack",
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    tags: ["standup", "team", "sprint"],
    has_pii: true,
    scores: { quality: 0.71 },
  },
  {
    id: "cap-5",
    category: "error",
    summary: "TypeError in capture pipeline",
    content: "TypeError: 'NoneType' object is not subscriptable at line 45 in capture_agent.py",
    source: "VS Code",
    timestamp: new Date(Date.now() - 28800000).toISOString(),
    tags: ["bug", "python", "pipeline"],
    has_pii: false,
    scores: { quality: 0.65 },
  },
  {
    id: "cap-6",
    category: "documentation",
    summary: "Google ADK — Agent Development Kit",
    content: "The Agent Development Kit provides tools for building, testing, and deploying AI agents...",
    source: "Chrome",
    timestamp: new Date(Date.now() - 36000000).toISOString(),
    tags: ["google", "adk", "agents"],
    has_pii: false,
    scores: { quality: 0.88 },
  },
];

export const mockUserModel = {
  role: "Fullstack Engineer",
  work_context: "Building AI agent systems at a startup",
  languages: ["Python", "TypeScript", "SQL"],
  interests: ["AI Agents", "LLMs", "Cooking", "Systems Design"],
  active_projects: ["Capsule — Self-Improving Agent", "Recipe Collection"],
  learned_facts: [
    { text: "Prefers Python for backend work", source: "inferred from captures", timestamp: new Date(Date.now() - 86400000).toISOString() },
    { text: "Interested in agent orchestration patterns", source: "inferred from captures", timestamp: new Date(Date.now() - 172800000).toISOString() },
    { text: "Uses VS Code as primary editor", source: "inferred from captures", timestamp: new Date(Date.now() - 259200000).toISOString() },
    { text: "Enjoys Italian cuisine", source: "inferred from captures", timestamp: new Date(Date.now() - 345600000).toISOString() },
    { text: "Works in sprints (agile methodology)", source: "inferred from captures", timestamp: new Date(Date.now() - 432000000).toISOString() },
    { text: "Reads academic papers regularly", source: "inferred from captures", timestamp: new Date(Date.now() - 518400000).toISOString() },
    { text: "Uses Slack for team communication", source: "inferred from captures", timestamp: new Date(Date.now() - 604800000).toISOString() },
    { text: "Interested in quality scoring systems", source: "you told me", timestamp: new Date(Date.now() - 50000000).toISOString() },
    { text: "Prefers TypeScript for frontend", source: "you told me", timestamp: new Date(Date.now() - 100000000).toISOString() },
  ],
  confidence: {
    code: 92,
    recipe: 78,
    research: 88,
    communication: 65,
    documentation: 85,
    error: 70,
    personal: 45,
    shopping: 30,
    reference: 55,
  },
  pending_questions: [
    "Do you prefer tabs or spaces in your code captures?",
    "Should I treat bookmarks differently from clipboard captures?",
  ],
};

export const mockMetrics = {
  total_captures: 113,
  reflections_triggered: 24,
  pii_caught: 7,
  facts_learned: 9,
  corrections_applied: 3,
  score_trend: [
    { time: "Day 1", score: 0.62 },
    { time: "Day 2", score: 0.65 },
    { time: "Day 3", score: 0.68 },
    { time: "Day 4", score: 0.71 },
    { time: "Day 5", score: 0.74 },
    { time: "Day 6", score: 0.76 },
    { time: "Day 7", score: 0.78 },
  ],
  avg_confidence: 78,
};

export const mockJudgePanel = {
  architecture: {
    coordinator: "CapsuleCoordinator",
    agents: ["ProcessCapture", "SearchAgent", "ChatAgent", "SynthesisAgent", "LearningAgent", "FeedAgent"],
    pipeline: ["Understand", "DLP", "Ingest", "QualityLoop"],
    quality_loop: ["Score", "Reflect", "Retry"],
  },
  sponsors: [
    { name: "Google", product: "Gemini 2.5 Flash + ADK", description: "Agent framework + LLM backbone", logo: "🔷" },
    { name: "Airia", product: "Understand + DLP Agents", description: "External specialist agents for classification and PII protection", logo: "🧠" },
    { name: "Braintrust", product: "Observability + Scoring", description: "Quality scoring, improvement tracking, experiment logging", logo: "📊" },
  ],
  improvement_loops: [
    { name: "Reflection", description: "Agent re-processes low-scoring captures", metric: "Score improved from 0.62 → 0.78", how: "When quality score drops below threshold, agent retries with refined prompt" },
    { name: "Synthesis", description: "Cross-capture pattern detection", metric: "8 insights generated", how: "Periodically analyzes capture clusters to find emergent themes" },
    { name: "Active Learning", description: "Agent asks clarifying questions", metric: "9 facts learned", how: "When uncertain about classification, asks user for guidance" },
    { name: "Human Feedback", description: "User corrections train the agent", metric: "3 corrections applied", how: "Tag corrections update classification rules for future captures" },
  ],
};
